//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace экзамен_слож
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Абоненты_КалмыковEntities : DbContext
    {
        public Абоненты_КалмыковEntities()
            : base("name=Абоненты_КалмыковEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Абонент> Абонент { get; set; }
        public virtual DbSet<Разговоры> Разговоры { get; set; }
        public virtual DbSet<Тариф> Тариф { get; set; }
        public virtual DbSet<Телефон> Телефон { get; set; }
    }
}
