//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace экзамен_слож
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефон
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Телефон()
        {
            this.Разговоры = new HashSet<Разговоры>();
        }
    
        public string Номер_Телефона { get; set; }
        public string Номер_договора { get; set; }
        public string Дата_установки { get; set; }
        public Nullable<int> Id_абонента { get; set; }
    
        public virtual Абонент Абонент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Разговоры> Разговоры { get; set; }
    }
}
